services:
  bs_commande-api:
    image: ghcr.io/maalsi23g1/commande_api/commande_service:latest
    user: root #A modifier plus tard
    container_name: bs_commande-api
    depends_on:
      bs_rabbitmq:
        condition: service_healthy
      bs_commande-mariaDb:
        condition: service_healthy				
    command: ["sh", "-c", "chown -R www-data:www-data var/cache var/log && chmod -R 775 var/cache var/log && chmod 1777 /tmp && php-fpm"]
    env_file:
      - ../.env
    networks:
      - bs-command-network
      - bs-broker-network
      - bs-logging-network

  bs_commande-nginx:
    image: nginx:stable
    container_name: bs_commande-nginx
    env_file:
      - ../.env
    ports:
      - '8080:80'
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - bs_commande-api
    networks:
      - bs-command-network
      - bs-gateway-network
      - bs-logging-network

  bs_commande-mariaDb:
    image: mariadb:latest
    container_name: bs_commande-mariaDb
    env_file:
      - ../.env
    ports:
      - '3306:3306'
    volumes:
      - ${COMMAND_VOLUME_HOST_PATH}:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro  # <-- Ajout du fichier d'init

    networks:
      - bs-command-network
      - bs-logging-network
    healthcheck:
      test: ["CMD", "mariadb", "-h", "localhost", "-u", "root", "-p${MARIADB_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 3


networks:
  bs-command-network:
    name:  bs-command-network
    driver: bridge
    internal: true