deploy_machine:
  hosts:    
# Déploiement sur Perso VPS
    home_vps:
      ansible_connection: ssh
      ansible_host: "{{ lookup('env', 'VPS_IP') }}"
      ansible_port: "{{ lookup('env', 'VPS_PORT') }}"
      ansible_user: "{{ lookup('env', 'VPS_USER') }}"
      ansible_python_interpreter: /usr/bin/python3
